services:
  - type: web
    name: ai-exam-system-backend
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: MONGODB_URI
        sync: false
      - key: ACCESS_TOKEN_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
